load("//moe/best/athenaeum/apptests:helpers.bzl", "athena_module_test")

athena_module_test(
    name = "youtube_test",
    srcs = glob(["**/*.kt"]),
    test_class = "moe.best.athenaeum.apptests.udc.social.YouTubeTest",
)